//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackathonCCR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hackathon_ccrEntities : DbContext
    {
        public hackathon_ccrEntities()
            : base("name=hackathon_ccrEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<endereco> endereco { get; set; }
        public virtual DbSet<pessoa> pessoa { get; set; }
        public virtual DbSet<pessoa_rodovia> pessoa_rodovia { get; set; }
        public virtual DbSet<pessoa_sente> pessoa_sente { get; set; }
        public virtual DbSet<rodovia> rodovia { get; set; }
        public virtual DbSet<sente> sente { get; set; }
    }
}
