//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackathonCCR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pessoa_rodovia
    {
        public int pessoaRodoviaId { get; set; }
        public int pessoaId { get; set; }
        public int rodoviaId { get; set; }
    
        public virtual pessoa pessoa { get; set; }
        public virtual rodovia rodovia { get; set; }
    }
}
