//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HackathonCCR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pessoa_sente
    {
        public int pessoaSenteId { get; set; }
        public int pessoaId { get; set; }
        public int senteId { get; set; }
        public System.DateTime data { get; set; }
    
        public virtual pessoa pessoa { get; set; }
        public virtual sente sente { get; set; }
    }
}
